
- name: Crear directorio alumno
  file:
    path: /tmp/2do_parcial/alumno
    state: directory
    mode: '0755'

- name: Crear directorio equipo
  file:
    path: /tmp/2do_parcial/equipo
    state: directory
    mode: '0755'

- name: Crear archivo datos_alumno.txt
  template:
    src: datos_alumno.txt.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt
    mode: '0644'

- name: Crear archivo datos_equipo.txt
  template:
    src: datos_equipo.txt.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt
    mode: '0644'

- name: Crear archivo de sudoers para el grupo 2PSupervisores si no existe
  file:
    path: /etc/sudoers.d/2psupervisores
    state: touch
    mode: '0440'
  become: true

- name: Configurar sudoers para el grupo 2PSupervisores
  lineinfile:
    path: /etc/sudoers.d/2psupervisores
    line: '%2PSupervisores ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: '/usr/sbin/visudo -cf %s'
  become: true
